POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Peter",
  "surname": "Parker",
  "emailAddress": "peter@test.pl"
}

###
GET http://localhost:8080/api/users/1
Content-Type: application/json

###
GET http://localhost:8080/api/users/?surnameFragment=Par
Content-Type: application/json

###
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "Spring in Action",
  "description": "Spring in Action",
  "type": "EBOOK",
  "price": "100 PLN"
}

###
GET http://localhost:8080/api/products/5
Content-Type: application/json

###
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "products": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ]
}
###

POST http://localhost:8080/api/products/1/files
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="pom.xml"

< ./pom.xml
--WebAppBoundary--